### PR TITLE
flakes: add lnbits-legend

### PR DESCRIPTION
**Pull request by MatthewCroughan**
This adds a project I've encouraged to use Flakes and Nix called "lnbits", to the searchable registry on search.nixos.org.

### CODE REVIEW

**Comment by ncfavier** [comment]
`services.lnbits.package` needs a `defaultText`.

**Comment by MatthewCroughan** [comment]
@ncfavier I've done what you suggested, so does this now look good to merge?

**Comment by MatthewCroughan** [comment]
@ncfavier There are already numerous, such as nix-bitcoin in the index. So you'll have to remove those too if you're going to make such a decision, otherwise what you have said is quite unfair.

**Comment by MatthewCroughan** [comment]
@jonasnick is the author of nix-bitcoin which is already included in the nixos-search index.

**Comment by MatthewCroughan** [comment]
@ncfavier If you want to ban cryptocurrency related projects from nixos-search, please add that to #486.

**Comment by erikarvstedt** [comment]
@ncfavier, what's the rationale for banning cryptocurrency projects from the Nix ecosystem?

One of the Flake design goals is a broadened, not a narrowed scope compared to nixpkgs, so shouldn't cryptocurrencies be banned from nixpkgs and NixOS first?

Tweag, the largest commercial actor in the nix ecosystem, is strongly associated with cryptocurrencies (i.e. Cardano and Tezos). How is this compatible with banning cryptocurrencies from Nix?

**Comment by Mic92** [comment]
I am ok with merging this when merge conflicts are resolved.

**Review by Mic92 — APPROVED** [review]

**Pull request merged**
