### PR TITLE
Fix wildcard search

### PR DESCRIPTION
**Pull request by ncfavier**
Fixes https://github.com/NixOS/nixos-search/issues/537 maybe.

### CODE REVIEW

**Comment by ysndr** [comment]
We had a wildcard search?

**Comment by ncfavier** [comment]
> We had a wildcard search?

Apparently.

> [wildcard] query does not support [case_insensitive]

Hmm, I guess we're using a version of Elastic older than 7.10.0? (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html)

**Comment by ncfavier** [comment]
Yeah, 7.2.0. Shame.

**Comment by ncfavier** [comment]
Maybe we can just remove the `lowercase` call in the frontend, so that we can at least match things using the proper capitalisation?

**Comment by ncfavier** [comment]
That seems to work. Now at least `extraDep` returns a result.

**Comment by ysndr** [comment]
@garbas is it possible to elevate us onto a newer elastic version?

**Comment by garbas** [comment]
There is `7.10.2` version available, would that work?

**Comment by ncfavier** [comment]
Yes!

**Comment by garbas** [comment]
Sorry I forgot to contact the Bonsai support, I've done it now. I'll keep you posted.

**Comment by ncfavier** [comment]
Maybe we can merge this in the meantime?

**Comment by garbas** [comment]
yeah, lets merge this. works a little better.

I also got news from bonsai (it for some reason went to my spam) that they will bring new cluster with 7.10 up. Then we will have to rework the query a bit.

**Review by garbas — APPROVED** [review]

**Pull request merged**
