### PR TITLE
Add kalker to the flakes index

### PR DESCRIPTION
**Pull request by Kloenk**
Kalker/kalk is a calculator with math syntax that supports user-defined variables and functions, complex numbers, and estimation of derivatives and integrals.

https://github.com/PaddiM8/kalker

### CODE REVIEW

**Comment by ysndr** [comment]
Relevant [reddit thread](https://www.reddit.com/r/rust/comments/pskqhk/comment/hdqc4l5?context=3)

**Comment by ysndr** [comment]
This flake is incompatible with the flake-info script

https://github.com/PaddiM8/kalker/blob/967b9f372b8967d1184e0796562b31d42ec0ddaf/flake.nix#L40

defines `packages` as `nixpkgs` whicle it should be an attr set of those packages build by that project (only kalker in this case)

**Review by ysndr — CHANGES_REQUESTED** [review]
Please change the `packages` attribute for this flake

https://github.com/PaddiM8/kalker/blob/967b9f372b8967d1184e0796562b31d42ec0ddaf/flake.nix#L40

**Comment by Kloenk** [comment]
My bad. Thought I did, will fix

**Review by ysndr — APPROVED** [review]
LGTM

Curently the frontend will only pick up derivation descriptions, therefore I recommend adding a description atrribute to the kalker derivation as well so we know what it is when it turns up in the search.

**Comment by Kloenk** [comment]
> Curently the frontend will only pick up derivation descriptions, therefore I recommend adding a description atrribute to the kalker derivation as well so we know what it is when it turns up in the search.


You mean the usual meta attribute as used in nixpkgs?

**Pull request merged**
