### PR TITLE
Search programs provided by a package

### PR DESCRIPTION
**Pull request by ncfavier**
Use the `programs.sqlite` database provided with nixpkgs channels to populate a `package_programs` field so that searches for e.g. `make` return `gnumake` with a higher priority.

Fixes https://github.com/NixOS/nixos-search/issues/577

### CODE REVIEW

**Comment by ncfavier** [comment]
Looking good: [make](https://63da79e576891a06bdfbf8d9--nixos-search.netlify.app/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=make).

As a nice side-effect this seems to make `bashInteractive` float to the top.

Checked the same things as [last time](https://github.com/NixOS/nixos-search/pull/584#issue-1502741342), no regressions.

**Comment by roberth** [comment]
I [dig](https://63da79e576891a06bdfbf8d9--nixos-search.netlify.app/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=dig) this.

Maybe show the list of programs when expanding the package details?

**Comment by ncfavier** [comment]
> I [dig](https://63da79e576891a06bdfbf8d9--nixos-search.netlify.app/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=dig) this.

Note that dig was already shown first since that's just the package's name.

> Maybe show the list of programs when expanding the package details?

Done.

[kaldi](https://63da963829572f07e9e3499e--nixos-search.netlify.app/packages?channel=unstable&show=kaldi&from=0&size=50&sort=relevance&type=packages&query=kaldi) has a lot of programs.

[roboto](https://63da963829572f07e9e3499e--nixos-search.netlify.app/packages?channel=unstable&show=roboto&from=0&size=50&sort=relevance&type=packages&query=roboto) has none.

**Comment by roberth** [comment]
> > I [dig](https://63da79e576891a06bdfbf8d9--nixos-search.netlify.app/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=dig) this.
> 
> Note that dig was already shown first since that's just the package's name.

I must have been thinking of `command-not-found`.

> > Maybe show the list of programs when expanding the package details?
> 
> Done.

It says "/bin" in the section title which is a little vague. It seems to only list the binaries of the selected output, so perhaps this can be prefixed to the "/bin" title?

It'd be nice for it to list other outputs too, and perhaps the things you need to do to actually get one of the alternative outputs. The latter is non-trivial, as it involves `meta.outputsToInstall` and both an expression- and a CLI use case.


(If you'd like to pursue these things; it's already a nice improvement; maybe a follow-up?)

-------


Example:

### `$bin/bin`

Example usage: `${lib.getBin foo}/cmd`, `environment.systemPackages = [ pkgs.foo ];`

### `$bar/bin`

This output is not installed by default.
Example usage: `${foo.bar}/cmd`, `environment.systemPackages = [ pkgs.foo.bar ];`, `nix profile install foo.bar`

(or maybe it should link to a `foo.bar` packages, as these are effectively distinct packages built by the same derivation) (also maybe it should be `nix-env` for now)

**Comment by ncfavier** [comment]
There's no selected output; the bold one is the *default* output (maybe it should just be listed first...). AFAICT nix-index amalgamates packages from all outputs: see [glib](https://63da963829572f07e9e3499e--nixos-search.netlify.app/packages?channel=unstable&show=glib&from=0&size=50&sort=relevance&type=packages&query=glib) (default `bin`) and [tzdata](https://63da963829572f07e9e3499e--nixos-search.netlify.app/packages?channel=unstable&show=tzdata&from=0&size=50&sort=relevance&type=packages&query=tzdata) (default `out`, programs in `bin`).

We could make `nix-index` add an `output` field to the database; not sure I'll have the motivation to follow up on that here though.

**Comment by fricklerhandwerk** [comment]
This is just lovely, thanks so much!

**Pull request merged**
