### PR TITLE
Remove reverse fields

### PR DESCRIPTION
**Pull request by ncfavier**
Their [initial](https://github.com/NixOS/nixos-search/pull/176) purpose was suffix queries, but this should be handled by the wildcard queries now.

### CODE REVIEW

**Comment by ncfavier** [comment]
No regression on https://github.com/NixOS/nixos-search/issues/537: [extradep](https://638f2d866db644172e05b49f--nixos-search.netlify.app/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=extradep)
No regression on https://github.com/NixOS/nixos-search/issues/170: [codium](https://638f2d866db644172e05b49f--nixos-search.netlify.app/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=codium)
[make](https://638f2d866db644172e05b49f--nixos-search.netlify.app/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=make) returns mostly `make*` rather than `*make` packages, but is otherwise still as unhelpful.

**Comment by ysndr** [comment]
Happy we can leave these reverse fields behind they were just noise in the code for the most part

**Review by garbas — APPROVED** [review]
:1st_place_medal: 

But lets test it in this PR before we merge it. Was the import already triggered?

**Comment by ncfavier** [comment]
Yes

**Comment by garbas** [comment]
Ignore my comment above. I didn't see you've already tested this.

**Pull request merged**
