### PR TITLE
release: 21.05 -> 21.11

### PR DESCRIPTION
**Pull request by tomberek**
cc: @garbas @ysndr @jonringer @nrdxp

### CODE REVIEW

**Comment by garbas** [comment]
@tomberek Usually we keep channel like `20.09` around for another month before we remove it. Can you only add `21.11` without removing `20.09`? Also can you add the `21.11` channel to `.github/workflows/cron-nixpkgs.yml` as well?

@ysndr initial 21.11 channel needs to be imported manually before we merge this PR. Otherwise the `21.11` index is going to be empty until github action populates it. Do you want manually import it or should I?

**Comment by garbas** [comment]
@tomberek to avoid ping/pong in comments I just fixed things myself.

**Comment by ysndr** [comment]
@garbas I'm just running the initial pull should be done in a couple minutes

**Comment by nrdxp** [comment]
@garbas @ysndr what is the status? We need to get this merged ASAP

**Review by ysndr — APPROVED** [review]

**Comment by ysndr** [comment]
@nrdxp there existed an index from a previous run that failed due to an internet outage. For some reason it coulndt be deleted (i still can't though even through REST?).
Luckily nixpkgs is on a new commit now so the import succeeded and we should be good to go  now

**Pull request merged**
