### PR TITLE
Add the 22.05 channel by updating the flake

### PR DESCRIPTION
**Pull request by dasJ**

### CODE REVIEW

**Comment by ncfavier** [comment]
Started an import on this branch.

**Comment by ncfavier** [comment]
It's trying to import `nixos-22.05` but that branch doesn't exist yet.

**Comment by dasJ** [comment]
Thanks, I will ping here again when Hydra pushed the channel

**Comment by dasJ** [comment]
Channel should be available now

**Review by ncfavier — APPROVED** [review]
Looks OK

**Comment by ysndr** [comment]
Since the 22.05 becomes stable on Monday (presumably) should we wait for stable and merge then?

**Comment by dasJ** [comment]
I actually think it would be better to merge this as-is. The reason is that the channel is clearly marked as Beta so it shouldn't matter as much and having the channel already available in the UI allows me to release 22.05 without having to wait for the PR to be merged in the configurations repo and then wait for the PR here. Telling users "it will still say beta although it's already released" is preferable to having to say "there is no search at all" imo. But that's my opinion, it's yours to decide

**Comment by ncfavier** [comment]
Fine with me.

**Pull request merged**
