### PR TITLE
Add nixos-mailserver to the flakes index

### PR DESCRIPTION
**Pull request by nlewo**
Here is the project: https://gitlab.com/simple-nixos-mailserver/nixos-mailserver

### CODE REVIEW

**Comment by ysndr** [comment]
Hej, I'm sorry this module definition is not compatible with flake-info as of now for two (maybe more) reasons related to option evaluation.

1. You have parts of the "implementation" in your config definition (https://gitlab.com/simple-nixos-mailserver/nixos-mailserver/-/blob/master/default.nix#L781-798).
This is: There is an evaluation of pkgs which should be happen only when writing the config i.e in `./mail-server/monit.nix`

2. Similarly you reference `cfg.fqnd` in definitions as default value while its value is not necessarily defined and has no default (same about [this](config.services.redis.bind) redis field.

Both problems mean that flake-info cannot evaluate the module. While `pkgs` could be passed into,  the evaluation, but is not canonical as far as I understand it. The issue with references to undefined cfg values can only be fixed on your end.

For both I'd assume that it is possible to move more of the "semantic" / "implementation" to the implementing config files in `./mail-server/*`

**Comment by ncfavier** [comment]
For the record, I opened https://gitlab.com/simple-nixos-mailserver/nixos-mailserver/-/merge_requests/259 upstream to fix the issues here

**Comment by garbas** [comment]
@nlewo @ncfavier any update on the upstream PR/MR?

**Comment by nlewo** [comment]
@ncfavier sorry, i should not have postponed your NixOS mailserver MR :(

I'm now on it and it's almost merged. @garbas we will provide an update here once merged.

**Review by ncfavier — APPROVED** [review]
`flake-info flake gitlab:simple-nixos-mailserver/nixos-mailserver` suceeds now

**Pull request merged**
