### PR TITLE
Improve nix.py

### PR DESCRIPTION
**Pull request by ncfavier**
Adds escaping of `\` and `"` inside double-quoted strings (see `system.name`), and fixes indentation for double-single-quoted strings and `literalExample`s (see `services.snapper.configs`).

### CODE REVIEW

**Comment by garbas** [comment]
@ncfavier can you add some tests for this use cases? Also if you can point to me which options are being fixed by this?

**Comment by ncfavier** [comment]
I did: `system.name` and `services.snapper.configs`. Where would you like me to add tests?

**Review by garbas — APPROVED** [review]
@ncfavier no worries. I've merged the master and added the tests.

I will run the import manually in few minutes.

**Comment by ncfavier** [comment]
Looks good to me!

**Pull request merged**
